"""Synthetic pilot data, for dry runs and demonstrations.

Every example in this repository runs on data generated here. No real
applicant data appears anywhere in the project, and none should ever be
committed to it.

Beyond demonstrations, this module exists because of step 6 of
``docs/Pilot-Deployment-Guide.md``: *dry-run summary report outputs with
synthetic or placeholder data* before touching live traffic. Generating a
pilot's worth of plausible events and running the real analysis over it lets
a team confirm the metric definitions produce the numbers they expect, and
see what the readout will look like, while there is still time to fix the
instrumentation.

The generator is seeded and therefore reproducible: the same seed yields the
same dataset, so an example report can be regenerated byte-for-byte and
checked in.
"""

from __future__ import annotations

import random
from collections.abc import Mapping
from datetime import datetime, timedelta, timezone

from .assignment import Assigner
from .config import ExperimentConfig
from .errors import ConfigError
from .events import EventLog

__all__ = ["SimulationSpec", "simulate_pilot"]


class SimulationSpec:
    """Ground-truth rates used to generate a synthetic pilot.

    Parameters are per-variant true rates. Because the truth is known, the
    output is useful for testing the analysis itself: a spec where control
    and treatment share a rate should mostly *not* produce a promote
    decision, and one with a large gap should.
    """

    def __init__(
        self,
        *,
        completion_rate: Mapping[str, float],
        error_rate: Mapping[str, float] | None = None,
        support_rate: Mapping[str, float] | None = None,
        median_seconds: Mapping[str, float] | None = None,
        segment_distribution: Mapping[str, Mapping[str, float]] | None = None,
        completion_overrides: Mapping[str, Mapping[str, float]] | None = None,
        unit_attributes: Mapping[str, object] | None = None,
        units: int = 2000,
        start: datetime | None = None,
        duration_days: int = 28,
        seed: int = 20260904,
    ) -> None:
        self.completion_rate = dict(completion_rate)
        self.error_rate = dict(error_rate or {})
        self.support_rate = dict(support_rate or {})
        self.median_seconds = dict(median_seconds or {})
        # Coded, non-identifying attributes recorded at assignment time, as
        # {dimension: {value: probability}}. These are what equity segment
        # analysis groups by.
        self.segment_distribution = {
            dim: dict(values) for dim, values in (segment_distribution or {}).items()
        }
        # Per-segment completion rates, as {"dimension=value": {variant: rate}}.
        # Lets a simulation model a change that helps one group and not another,
        # which is the case the equity review exists to catch.
        self.completion_overrides = {
            key: dict(rates) for key, rates in (completion_overrides or {}).items()
        }
        # Applied to every synthetic unit. Must satisfy the config's
        # eligibility criteria, or the simulation produces no enrolled units.
        self.unit_attributes = dict(unit_attributes or {})
        self.units = units
        self.start = start or datetime(2026, 3, 2, 9, 0, tzinfo=timezone.utc)
        self.duration_days = duration_days
        self.seed = seed


def _draw(rng: random.Random, distribution: Mapping[str, float]) -> str:
    """Pick a value from a {value: probability} mapping."""
    threshold = rng.random() * sum(distribution.values())
    cumulative = 0.0
    for value, weight in distribution.items():
        cumulative += weight
        if threshold < cumulative:
            return value
    return next(iter(distribution))


def simulate_pilot(
    config: ExperimentConfig,
    spec: SimulationSpec,
    *,
    path: str | None = None,
) -> EventLog:
    """Generate a synthetic but internally consistent pilot dataset."""
    rng = random.Random(spec.seed)
    assigner = Assigner(
        salt=config.salt,
        variants=config.variants,
        eligibility=config.eligibility,
        enrolled_fraction=config.enrolled_fraction,
    )
    log = EventLog(
        config.experiment_id,
        path=path,
        privacy=config.privacy,
        allowed_variants=config.variants,
    )

    window = timedelta(days=spec.duration_days)
    for index in range(spec.units):
        unit_id = f"synthetic-unit-{index:06d}"
        assignment = assigner.assign(unit_id, spec.unit_attributes)
        if not assignment.in_analysis:
            continue

        variant = assignment.variant
        started = spec.start + window * rng.random()
        pseudonym = assignment.unit_pseudonym

        # Draw this unit's segment values and record them on the entry event,
        # which is where segment analysis reads them from.
        segments: dict[str, str] = {}
        for dimension, distribution in spec.segment_distribution.items():
            segments[dimension] = _draw(rng, distribution)

        log.record(
            "experiment_assigned", pseudonym, variant, timestamp=started,
            payload=segments,
        )
        log.record(
            "step_viewed",
            pseudonym,
            variant,
            timestamp=started + timedelta(seconds=rng.uniform(1, 20)),
            step="document_upload",
        )

        # A segment override, if one applies to this unit, replaces the
        # variant-level completion rate.
        rate = spec.completion_rate.get(variant, 0.5)
        for dimension, value in segments.items():
            override = spec.completion_overrides.get(f"{dimension}={value}")
            if override and variant in override:
                rate = override[variant]
                break
        completed = rng.random() < rate
        errored = rng.random() < spec.error_rate.get(variant, 0.0)
        contacted = rng.random() < spec.support_rate.get(variant, 0.0)

        # Log-normal durations: service task times are right-skewed, so a
        # symmetric distribution would understate the long tail that drives
        # abandonment.
        median = spec.median_seconds.get(variant, 300.0)
        elapsed = median * min(rng.lognormvariate(0.0, 0.6), 12.0)

        if errored:
            log.record(
                "submission_failed",
                pseudonym,
                variant,
                timestamp=started + timedelta(seconds=elapsed * 0.7),
                failure_kind="blocking_error",
            )
        if contacted:
            log.record(
                "support_contacted",
                pseudonym,
                variant,
                timestamp=started + timedelta(seconds=elapsed * 0.8),
                channel="phone",
            )
        if completed:
            log.record(
                "submission_attempted",
                pseudonym,
                variant,
                timestamp=started + timedelta(seconds=elapsed * 0.95),
            )
            log.record(
                "step_completed",
                pseudonym,
                variant,
                timestamp=started + timedelta(seconds=elapsed),
                step="document_upload",
            )
            log.record(
                "submission_succeeded",
                pseudonym,
                variant,
                timestamp=started + timedelta(seconds=elapsed),
            )

    if not len(log):
        raise ConfigError(
            f"the simulation enrolled none of its {spec.units} synthetic units. The "
            "eligibility criteria reference attributes that SimulationSpec."
            "unit_attributes does not supply, so every unit was excluded. Pass "
            "attributes that satisfy the criteria: "
            f"{sorted(config.eligibility.referenced_fields())}",
            code="CONFIG_SIMULATION_EMPTY",
        )
    return log
